# PostgreSQL. Versions 9.3 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
default: &default
  adapter: postgresql
  encoding: unicode
  # These values will be overridden by DATABASE_URL if present
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: support_ticketing_backend_development

test:
  <<: *default
  database: support_ticketing_backend_test

# In production, we use the DATABASE_URL provided by Render
production:
  # If DATABASE_URL is present, Rails will use it automatically
  # and override the values above
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: <%= ENV.fetch("DB_NAME") { "support_ticketing_production" } %>
  # Larger connection pool for production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
